### ISSUE TITLE
Stuck on Starting Server

### ISSUE THREAD

**Issue by georgewoofbates** [scosman/zipstreamer#34]
First off, just wanted to say thanks this is such a useful repo! I've managed to deploy using Google Cloud run for testing and works great.

Only issue I'm having is trying to run it elsewhere. I want to run on AWS as that's where the rest of my infrastructure is, but when I try to run on an EC2 instance, on App Runner or on my MacBook locally, it just gets stuck on Server starting on port 8080.

Any ideas what might be causing that?

**Comment by scosman** [comment]
Are you sure it's actually stuck and not just running? When it successfully starts the last log you'll see is `Server starting on port xxxx`, and that usually indicates it's up and running. Nothing else will be logged until a request comes in.

**Comment by scosman** [comment]
Quickest way to check is just open `http://localhost:8008` -- if you get a 404 it's running fine and should server valid requests.
